export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";


export const FETCH_CANDIDATES_START  = "FETCH_CANDIDATES_START";
export const FETCH_CANDIDATES  = "FETCH_CANDIDATES_START";
export const FETCH_CANDIDATES_SUCCESS  = "FETCH_CANDIDATES_SUCCESS";
export const FETCH_CANDIDATES_FAIL  = "FETCH_CANDIDATES_FAIL";


export const FETCH_CANDIDATE_IMAGE_START  = "FETCH_CANDIDATE_IMAGE_START";
export const FETCH_CANDIDATE_IMAGE  = "FETCH_CANDIDATE_IMAGE";
export const FETCH_CANDIDATE_IMAGE_SUCCESS  = "FETCH_CANDIDATE_IMAGE_SUCCESS";
export const FETCH_CANDIDATE_IMAGE_FAIL  = "FETCH_CANDIDATE_IMAGE_FAIL";
